Auth social
Dasha1801/task1-as-reddit pull request #9
Opened 2022-02-22 17:53 UTC by Dasha1801

1. Deploy: https://as-reddit.netlify.app/
2. Аутентификация через google, fb.
3. Сверстана вся боковая панель.
4. Items боковой панели можно перемещать (кроме компонента Filters);
5. В компонент Filter добавлен dnd без сторонних библиотек.
6. Добавлена анимация в блок с правилами.
7. Тесты для новых компонентов.

2022-02-24 06:45 UTC, YuriyBC requested changes

2022-02-24 06:45 UTC, YuriyBC commented on client/src/components/authSocialButtons/socialButtons.tsx
> +  const stylesBtn = { height: '35px', fontSize: '17px' };
через классы, незачем инлайн

2022-02-24 06:45 UTC, YuriyBC commented on client/src/components/authSocialButtons/socialButtons.tsx
> +    if (action === 'signUp' && profile.email) {
signUp и logIn можно вынести в enum

2022-02-24 06:45 UTC, YuriyBC commented on client/src/components/authSocialButtons/socialButtons.tsx
> +    handleLogin();
handleLogin() это субмит экшен; его желательно вызывать не черз юсЭффект, а через конкретныое действие, например клик (в данном случае onResolve)

2022-02-24 06:45 UTC, YuriyBC commented on client/src/components/authSocialButtons/socialButtons.tsx
> +          console.log(err);
желательно показывать снекбрар в случае ошибки

2022-02-24 06:45 UTC, YuriyBC commented on client/src/components/authSocialButtons/socialButtons.tsx
> +          console.log(err);
желательно показывать снекбрар в случае ошибки

2022-02-24 06:45 UTC, YuriyBC commented on client/src/components/communityBlock/community.tsx
> +        <CSSTransition in={show} timeout={1000} classNames="animation-item" unmountOnExit appear>
timeout вынести на уровень констант и переисползовать

2022-02-24 06:45 UTC, YuriyBC commented on client/src/components/filterBlock/filter.scss
> +    opacity: 0.45;
слишком специфично) давай 0.5

2022-02-24 06:45 UTC, YuriyBC commented on client/src/components/filterBlock/filter.tsx
> +            draggable
одинарные true пропсы должны быть вверху елемента

2022-02-24 06:45 UTC, YuriyBC commented on client/src/components/forms/tests/formSignUp.test.tsx
> +    expect(screen.getByTestId('variants')).toBeInTheDocument();
нужно затестить список городов который отображается, а также то, что при клике он вставляется в форму.

2022-02-24 06:45 UTC, YuriyBC commented on client/src/components/forms/validate/validateUpdate.ts
> +      const isCityValid = value && findCity(value);
луче сразу (value && findCity(value)) !== -1

2022-02-24 06:45 UTC, YuriyBC commented on client/src/components/modal/test/modalLogin.test.tsx
> +    expect(screen.getByText('LOG IN')).toBeInTheDocument();
лучше оставить как было - /log in/i
так как он дает большую гибкость. когда вдруг поменяешь стрингу в коде, не придется править тест

2022-02-24 06:45 UTC, YuriyBC commented on client/src/components/forms/tests/formSignUp.test.tsx
> +    expect(screen.getByTestId('variants')).toBeInTheDocument();
нужно затестить список городов который отображается, а также то, что при клике он вставляется в форму.

2022-02-24 06:45 UTC, YuriyBC commented on client/src/components/redux/asyncActions.ts
> +      console.log('User unregister!');
нужно показывать снекбар (а для этого нужно вынести снекбар в отдельный компонент, который рендерится в руте на каждой странице однако отображается только тогда, когда в редаксе включен соотвестующий флаг

2022-02-24 06:45 UTC, YuriyBC commented on client/src/components/redux/asyncActions.ts
> +      console.log('User unregister!');
этого не было в требованиях, скорее небольшой импрувмент

2022-02-24 06:45 UTC, YuriyBC commented
1. При перетаскивании Filter by flair нет border-radius у айтема
2. Текста шторки должен быть кликабелен (сейчас кликабельна только иконка)
3. При лоадинге страницы правый блок исчезает на мгновенье, нужно исправить
4. Внутри всех itemSidebar у тебя классы то tableWrapper, то contentSidebar, то contentFilter, все разные, хотя паддинг внутри у всех одинаковый (12px). Нужно все повторяющиеся стили контент-враппера добавить в один класс и использовать его между всех сайд-блоков. Если для конкретного сайдбара нужны другие стили - это уже второй класс
![image](https://user-images.githubusercontent.com/20384938/155469270-5e07e0a5-686f-448d-b8da-d2dd36ab6291.png)
5. при регистрации при очистке формы города айтемы из саджеста все еще отображаются

2022-02-24 08:27 UTC, Dasha1801 commented on client/src/components/authSocialButtons/socialButtons.tsx
> +  const stylesBtn = { height: '35px', fontSize: '17px' };
не могу, тк из коробки кнопки, и в них инлайн заданы дефолтные стили, перебить могу только тоже инлайн

2022-02-24 08:27 UTC, Dasha1801 commented on client/src/components/authSocialButtons/socialButtons.tsx
> +    if (action === 'signUp' && profile.email) {
+

2022-02-24 09:08 UTC, Dasha1801 commented on client/src/components/authSocialButtons/socialButtons.tsx
> +    if (action === 'signUp' && profile.email) {
вынесла

2022-02-24 09:11 UTC, Dasha1801 commented on client/src/components/authSocialButtons/socialButtons.tsx
> +    handleLogin();
в onResolve происходит set данных профиля, handleLogin там не отрабатывает, по-этому и лежит в useEffect

2022-02-24 09:18 UTC, Dasha1801 commented on client/src/components/authSocialButtons/socialButtons.tsx
> +          console.log(err);
у меня показывается снекбар  и обрабатывается ошибка в другом компоненте(Form), если ошибка аутентификации - она обрабатывается в своем родном окне из коробки. Может я неправильно тебя поняла?

2022-02-24 09:18 UTC, Dasha1801 commented on client/src/components/authSocialButtons/socialButtons.tsx
> +          console.log(err);
у меня показывается снекбар  и обрабатывается ошибка в другом компоненте(Form), если ошибка аутентификации - она обрабатывается в своем родном окне из коробки. Может я неправильно тебя поняла?

2022-02-24 09:46 UTC, Dasha1801 commented on client/src/components/communityBlock/community.tsx
> +        <CSSTransition in={show} timeout={1000} classNames="animation-item" unmountOnExit appear>
сделано

2022-02-24 09:47 UTC, Dasha1801 commented on client/src/components/filterBlock/filter.scss
> +    opacity: 0.45;
сделано

2022-02-24 09:51 UTC, Dasha1801 commented on client/src/components/filterBlock/filter.tsx
> +            draggable
исправила

2022-02-24 10:30 UTC, Dasha1801 commented on client/src/components/forms/tests/formSignUp.test.tsx
> +    expect(screen.getByTestId('variants')).toBeInTheDocument();
затестила

2022-02-24 10:36 UTC, Dasha1801 commented on client/src/components/forms/validate/validateUpdate.ts
> +      const isCityValid = value && findCity(value);
изменила

2022-02-24 10:49 UTC, Dasha1801 commented on client/src/components/modal/test/modalLogin.test.tsx
> +    expect(screen.getByText('LOG IN')).toBeInTheDocument();
с флагом i у меня 3 совпадения, добавила  проверку на getAll

2022-02-24 10:50 UTC, Dasha1801 commented on client/src/components/forms/tests/formSignUp.test.tsx
> +    expect(screen.getByTestId('variants')).toBeInTheDocument();
есть

2022-02-24 10:52 UTC, Dasha1801 commented on client/src/components/redux/asyncActions.ts
> +      console.log('User unregister!');
это требование было, все есть, это popoverSlice

2022-02-25 06:11 UTC, YuriyBC commented on client/src/components/authSocialButtons/socialButtons.tsx
> +          console.log(err);
но насколько я понял, у тебя не обрабатывается эта ошибка, так что снекбар нужно показывать и здесь

2022-02-25 06:12 UTC, YuriyBC commented on client/src/components/authSocialButtons/socialButtons.tsx
> +          console.log(err);
но насколько я понял, у тебя не обрабатывается эта ошибка, так что снекбар нужно показывать и здесь

2022-02-25 06:16 UTC, YuriyBC commented on client/src/components/modal/test/modalLogin.test.tsx
> +    expect(screen.getByText('LOG IN')).toBeInTheDocument();
тогда желательно добавить уникальный идентификатор кнопки через data-test-id

2022-02-25 09:01 UTC, merged